### ISSUE TITLE
yarn support

### ISSUE THREAD

**Issue by maddhruv** [ClearTax/install-types#6]
Install types can be used with `yarn` as well.
Let's add support for that with something like `npx install-types --yarn`

**Comment by aditya81070** [comment]
@maddhruv are you talking about the installation of dependencies using yarn?

**Comment by maddhruv** [comment]
@aditya81070 yes, we can also look for `yarn.lock` as if it is available, install-types shall use that
otherwise option should be there

**Comment by aditya81070** [comment]
@maddhruv That is good idea. I am taking this issue. Please assign.

**Comment by aditya81070** [comment]
@maddhruv I was thinking about the use cases. I think we should install dependency using yarn when user provides `--yarn` option because there may be a case when `yarn.lock` is downloaded from a repo but the user doesn't have yarn installed. In this case, detecting yarn.lock and installing dependencies using yarn is a bad idea.

**Comment by maddhruv** [comment]
Please check the description, what I said there

**Comment by maddhruv** [comment]
Shipped with https://github.com/ClearTax/install-types/releases/tag/2.0.0
